### PR TITLE
bringing over recent posts from current centexgis site

### PR DESCRIPTION
**Pull request by jwhaney**
3 posts brought over from centexgis site.

### CODE REVIEW

**Comment by jwhaney** [comment]
whoops, ignore my branch name. i have another PR that I am planning to submit to change out the current readme on the prototype2 repo to the same one as the centexgis.github.io repo; but i plan to keep the basically-basic documentation in another readme called basically-basic-readme. or we could move it over to the wiki tab for this repo.

**Review by AubreyRhea — COMMENTED** [review]
Could you merge this branch into your personal gh-pages branch so I can preview it at http://johnwhaney.com/prototype2/? Thanks!

**Comment by jwhaney** [comment]
yep, i can do that

**Comment by jwhaney** [comment]
merged

**Review by AubreyRhea — APPROVED** [review]
Looks great, let's merge it!

**Pull request merged**
