### PR TITLE
membership form edits; add zip code to front end form and...

### PR DESCRIPTION
**Pull request by jwhaney**
completed necessary edits to mail chimp backend to populate zip codes into contacts database.

test form submission using local web server successful / test submission populated contact database with zip, etc. testing forked gh-pages and also worked.

next step is to figure out how to pull zip codes collected in this form into geojson or some form for mapping in the atx-map repo which is embedded in the about page.

### CODE REVIEW

**Comment by jwhaney** [comment]
test out my gh-pages fork at: http://johnwhaney.com/prototype2/membership.html

**Comment by jwhaney** [comment]
screen shot of mailchimp backend; successful test.

image

**Comment by AubreyRhea** [comment]
I'm getting a captcha error in your fork at http://johnwhaney.com/prototype2/membership.html
image

**Comment by jwhaney** [comment]
can you provide a screenshot of the error in your browser console? i've tested the form and captcha a few times now and haven't gotten any error.

**Review by AubreyRhea — APPROVED** [review]
When tested some more, I realized I was getting the captcha error because I had pop-ups blocked. After I unblocked them, I was able to submit the form, and it sent me an email link to update my profile because I was using the same email address. The "update profile" form also included the new zip code field, and and I see it's populated in the database on the backend now too.

**Comment by jwhaney** [comment]
ok cool, so you think it's good to merge?

**Pull request merged**
