### PR TITLE
Improve banner, select posts by category from menu (category filter), add atxgis day post w/ flicker 

### PR DESCRIPTION
**Pull request by AubreyRhea**
I commented out the line in the stylesheet which was placing the green color wash over the banner image, changed the path so the images in the last post will show up, and added a new post.

### CODE REVIEW

**Comment by jwhaney** [comment]
Sorry it's taken awhile for me to look these over.

So just a suggestion based on information I've learned from others, but each pull request (PR) should probably only include edits/commits to just one file, which keeps it easier for others to review. This pull request has 17 commits to 9 files. You can have as many commits as you want in a pull request, but when there are a lot of commits and a lot of files in a PR, it gets confusing to make sense of. To get around that, you just create a branch for each pull request which includes edits/commits to one file. This keeps reviews easy and quick. Think of a PR as one item on a to-do list. Example: the banner change you made initially would be a PR by itself. I take a quick look and I go great awesome job, very easy to review, Merge it, boom done. Then a new PR is open for the font idea you had in the menu. Make it smaller open PR for that, review, boom, done.

I changed the name of this PR to reflect the changes going on. Let's plan to do this in the future, PR should be descriptive of the changes planning to occur once the PR is merged.

**Comment by jwhaney** [comment]
Additionally, it might be better for you to send me your live link in your forked repo (I'm assuming I can see it at https://aubreyrhea.github.io/prototype2?) because I can't view it here since it doesn't exist yet...? 

Maybe I'm confusing myself, it's been awhile since I've messed with this.... I guess I need to fork your repo maybe.

**Comment by jwhaney** [comment]
chrome_dev

So i'm looking it your forked gh-pages live site (https://aubreyrhea.github.io/prototype2) and there are some errors that I think are just bad paths to images in posts. Take a look. The image errors occur on the main page, Events, and Jobs pages. 

Also, on the About page, the map has been blocked due to a mixed content error (http vs. https). I think you might be able to fix that with changing the url to the map from http://centexgis.com/atx-map ---> https://centexgis.github.io/atx-map. If that doesn't work, then we can look at something else. It's not that big of a deal because if we incorporated it as is, it would work since the domain (CNAME file) makes the site repo unsecured http at centexgis.com.

**Comment by jwhaney** [comment]
If we can knock those errors out, I say we merge it. I think this looks really good! I'm glad that it looks like you figured out the ability to separate the posts by category and can do it from the menu now. Awesome.

**Comment by AubreyRhea** [comment]
Ok great, I will amend this pull request to fix those errors, and then merge it. In the future I will create separate branches and make separate pull requests for each change to each file, like you described.

**Comment by jwhaney** [comment]
Cool thank you. I guess since we are dealing with Jekyll, fixing one issue or making one enhancement/improvement may require editing more than one file. So I guess I should have said that each PR should be focused on one topic - ie. improve banner or make font smaller in menu, etc.

Thanks and great work!

**Comment by AubreyRhea** [comment]
If I change the URL to https://centexgis.github.io/atx-map the map doesn't load. https://aubreyrhea.github.io/prototype2/about.html

It looks like this maybe can't be fixed since we can't load custom domains over https and we can't load github.io pages over http. https://github.com/isaacs/github/issues/156 Let me know if you have any ideas.

**Comment by jwhaney** [comment]
Ya, I thought that might happen. I would say let's go ahead and merge and see what happens because it will end up unsecured when merged so it shouldn't be blocked. 

I read through that github issue you linked to and it seems like if we want to later we can look into adding a certificate to make the custom domain secured with https, but it seems it is not fully supported yet by GitHub, but might still be possible.

**Comment by jwhaney** [comment]
Looks good, map works. I added another issue that we can work on now. Disqus comments don't seem to be working for some reason. Might be a problem on the Disqus side, not sure.

**Pull request merged**
